version: '3.2'

services:
    
  appapi:
    build: .
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    container_name: appapi
    ports:
      - "8080:8080"
    environment:
      - APIHOST=0.0.0.0
      - APIPORT=8080
      - MYVAR=hello from docker compose
    volumes:
      - ./conf:/usr/src/appapi/conf:ro
    tty: true
